name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t tourism-app .
      - name: Run ETL and tests
        run: |
          docker-compose up -d db
          docker-compose run etl
          docker-compose run app pytest tests/
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag tourism-app ${DOCKER_USERNAME}/tourism-app:latest
          docker push ${DOCKER_USERNAME}/tourism-app:latest